FROM ghcr.io/pytorch/pytorch-nightly:latest

RUN apt-get update

RUN mkdir -p /usr/src/app/
COPY . /usr/src/app/
WORKDIR /usr/src/app/

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONBUFFERED 1

RUN pip install --upgrade pip

RUN pip install networkx diffusers transformers accelerate scipy safetensors gradio

RUN pip install -U xformers --index-url https://download.pytorch.org/whl/cu118